# Generated by Django 6.0.4 on 2026-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Stored copy of the uploaded PDF.', null=True, upload_to='policy_pdfs/'),
        ),
    ]
